// Generated by gencpp from file car_navigation/PoseAngle.msg
// DO NOT EDIT!


#ifndef CAR_NAVIGATION_MESSAGE_POSEANGLE_H
#define CAR_NAVIGATION_MESSAGE_POSEANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace car_navigation
{
template <class ContainerAllocator>
struct PoseAngle_
{
  typedef PoseAngle_<ContainerAllocator> Type;

  PoseAngle_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)
    , z(0)  {
    }
  PoseAngle_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)
    , z(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::car_navigation::PoseAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_navigation::PoseAngle_<ContainerAllocator> const> ConstPtr;

}; // struct PoseAngle_

typedef ::car_navigation::PoseAngle_<std::allocator<void> > PoseAngle;

typedef boost::shared_ptr< ::car_navigation::PoseAngle > PoseAnglePtr;
typedef boost::shared_ptr< ::car_navigation::PoseAngle const> PoseAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_navigation::PoseAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_navigation::PoseAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_navigation::PoseAngle_<ContainerAllocator1> & lhs, const ::car_navigation::PoseAngle_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_navigation::PoseAngle_<ContainerAllocator1> & lhs, const ::car_navigation::PoseAngle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::car_navigation::PoseAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_navigation::PoseAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_navigation::PoseAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_navigation::PoseAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_navigation::PoseAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_navigation::PoseAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_navigation::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bc475458b5903331d7038ac20f26588";
  }

  static const char* value(const ::car_navigation::PoseAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bc475458b590333ULL;
  static const uint64_t static_value2 = 0x1d7038ac20f26588ULL;
};

template<class ContainerAllocator>
struct DataType< ::car_navigation::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_navigation/PoseAngle";
  }

  static const char* value(const ::car_navigation::PoseAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_navigation::PoseAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 angle\n"
"uint8 z\n"
;
  }

  static const char* value(const ::car_navigation::PoseAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_navigation::PoseAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_navigation::PoseAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_navigation::PoseAngle_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "z: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_NAVIGATION_MESSAGE_POSEANGLE_H
